/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Î¢ÈíweiruanºÚ16.c                                          *
* Font:        Î¢ÈíweiruanºÚ                                              *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x41 (65)                                     *
* Character enabled:   0x42 (66)                                     *
* Character enabled:   0x40 (64)                                     *
* Character disabled:  0x40 (64)                                     *
* Character enabled:   0x50 (80)                                     *
* Character disabled:  0x50 (80)                                     *
* Character enabled:   0x70 (112)                                    *
* Read pattern file: C:\Users\er-ya\Desktop\11                       *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontweiruan16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0030[  8] = { /* code 0030, DIGIT ZERO */
  _XXX____,
  XX_XX___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  XX_XX___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0031[  8] = { /* code 0031, DIGIT ONE */
  __X_____,
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0032[  8] = { /* code 0032, DIGIT TWO */
  XXX_____,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  _X______,
  X_______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0033[  8] = { /* code 0033, DIGIT THREE */
  _XX_____,
  X__X____,
  ___X____,
  _XX_____,
  ___X____,
  ___X____,
  X__X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0034[  8] = { /* code 0034, DIGIT FOUR */
  ____X___,
  ___XX___,
  __X_X___,
  _X__X___,
  _X__X___,
  XXXXXX__,
  ____X___,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0035[  8] = { /* code 0035, DIGIT FIVE */
  XXXX____,
  X_______,
  X_______,
  XXX_____,
  ___X____,
  ___X____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0036[  8] = { /* code 0036, DIGIT SIX */
  __XXX___,
  _X______,
  X_______,
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0037[  8] = { /* code 0037, DIGIT SEVEN */
  XXXX____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0038[  8] = { /* code 0038, DIGIT EIGHT */
  _XXX____,
  X___X___,
  X___X___,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0039[  8] = { /* code 0039, DIGIT NINE */
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ____X___,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_003A[  5] = { /* code 003A, COLON */
  X_______,
  ________,
  ________,
  ________,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_003B[  6] = { /* code 003B, SEMICOLON */
  _X______,
  ________,
  ________,
  _X______,
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_003C[  5] = { /* code 003C, LESS-THAN SIGN */
  ____X___,
  __XX____,
  _X______,
  X_______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_003D[  3] = { /* code 003D, EQUALS SIGN */
  XXXXX___,
  ________,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_003E[  5] = { /* code 003E, GREATER-THAN SIGN */
  X_______,
  _XX_____,
  ___X____,
  ____X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_003F[  8] = { /* code 003F, QUESTION MARK */
  _XX_____,
  X__X____,
  ___X____,
  __X_____,
  _X______,
  _X______,
  ________,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0041[  8] = { /* code 0041, LATIN CAPITAL LETTER A */
  ___X____,
  __X_X___,
  __X_X___,
  __X_X___,
  _X___X__,
  _XXXXX__,
  _X___X__,
  X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0042[  8] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXX____,
  X__X____,
  X__X____,
  XXX_____,
  X__X____,
  X__X____,
  X__X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0043[  8] = { /* code 0043, LATIN CAPITAL LETTER C */
  __XXXX__,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0044[  8] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXX____,
  X___X___,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X___X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0045[  8] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXX____,
  X_______,
  X_______,
  XXXX____,
  X_______,
  X_______,
  X_______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0046[  8] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXX____,
  X_______,
  X_______,
  X_______,
  XXXX____,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0047[  8] = { /* code 0047, LATIN CAPITAL LETTER G */
  __XXX___,
  _X___X__,
  X_______,
  X_______,
  X__XXX__,
  X____X__,
  _X___X__,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0048[  8] = { /* code 0048, LATIN CAPITAL LETTER H */
  X____X__,
  X____X__,
  X____X__,
  XXXXXX__,
  X____X__,
  X____X__,
  X____X__,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0049[  8] = { /* code 0049, LATIN CAPITAL LETTER I */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_004A[  8] = { /* code 004A, LATIN CAPITAL LETTER J */
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_004B[  8] = { /* code 004B, LATIN CAPITAL LETTER K */
  X___X___,
  X__X____,
  X_X_____,
  XX______,
  XX______,
  X_X_____,
  X__X____,
  X___X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_004C[  8] = { /* code 004C, LATIN CAPITAL LETTER L */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_004D[  8] = { /* code 004D, LATIN CAPITAL LETTER M */
  XX_____X,
  XXX___XX,
  X_X___XX,
  X_X__X_X,
  X_XX_X_X,
  X__X_X_X,
  X__XX__X,
  X___X__X};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_004E[  8] = { /* code 004E, LATIN CAPITAL LETTER N */
  XX___X__,
  XXX__X__,
  X_X__X__,
  X_XX_X__,
  X__X_X__,
  X__X_X__,
  X___XX__,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_004F[  8] = { /* code 004F, LATIN CAPITAL LETTER O */
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0050[  8] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  XXXX____,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0051[  9] = { /* code 0051, LATIN CAPITAL LETTER Q */
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXXX__,
  ______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0052[  8] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  XXXX____,
  X__X____,
  X___X___,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0053[  8] = { /* code 0053, LATIN CAPITAL LETTER S */
  _XXXX___,
  X_______,
  X_______,
  _XX_____,
  ___X____,
  ____X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0054[  8] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0055[  8] = { /* code 0055, LATIN CAPITAL LETTER U */
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0056[  8] = { /* code 0056, LATIN CAPITAL LETTER V */
  X_____X_,
  _X___X__,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  __X_X___,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0057[ 16] = { /* code 0057, LATIN CAPITAL LETTER W */
  X____X__,_X______,
  X____X__,_X______,
  X___XXX_,X_______,
  _X_X__X_,X_______,
  _X_X__X_,X_______,
  _X_X__XX,X_______,
  _XX____X,________,
  __X____X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0058[  8] = { /* code 0058, LATIN CAPITAL LETTER X */
  X____X__,
  _X__X___,
  _X_X____,
  __XX____,
  __XX____,
  __XX____,
  _X__X___,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0059[  8] = { /* code 0059, LATIN CAPITAL LETTER Y */
  X____X__,
  _X__X___,
  _XX_X___,
  __X_X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_005A[  8] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXXXX__,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  _X______,
  X_______,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_005B[ 10] = { /* code 005B, LEFT SQUARE BRACKET */
  XX______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_005C[  9] = { /* code 005C, REVERSE SOLIDUS */
  X_______,
  XX______,
  _X______,
  _X______,
  _XX_____,
  __X_____,
  __X_____,
  __XX____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_005D[ 10] = { /* code 005D, RIGHT SQUARE BRACKET */
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_005E[  4] = { /* code 005E, CIRCUMFLEX ACCENT */
  __X_____,
  _X_X____,
  _X_X____,
  X___X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_005F[  1] = { /* code 005F, LOW LINE */
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0060[  2] = { /* code 0060, GRAVE ACCENT */
  XX______,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0061[  5] = { /* code 0061, LATIN SMALL LETTER A */
  _XXXX___,
  ____X___,
  _XXXX___,
  X___X___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0062[  8] = { /* code 0062, LATIN SMALL LETTER B */
  X_______,
  X_______,
  X_______,
  X_XX____,
  XX__X___,
  X___X___,
  X___X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0063[  5] = { /* code 0063, LATIN SMALL LETTER C */
  _XXX____,
  X_______,
  X_______,
  X_______,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0064[  8] = { /* code 0064, LATIN SMALL LETTER D */
  ___X____,
  ___X____,
  ___X____,
  _XXX____,
  X__X____,
  X__X____,
  X__X____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0065[  5] = { /* code 0065, LATIN SMALL LETTER E */
  _XXX____,
  X___X___,
  XXXXX___,
  X_______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0066[  8] = { /* code 0066, LATIN SMALL LETTER F */
  _XX_____,
  _X______,
  _X______,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0067[  7] = { /* code 0067, LATIN SMALL LETTER G */
  _XXX____,
  X__X____,
  X__X____,
  X__X____,
  _XXX____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0068[  8] = { /* code 0068, LATIN SMALL LETTER H */
  X_______,
  X_______,
  X_______,
  XXXX____,
  X__X____,
  X__X____,
  X__X____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0069[  8] = { /* code 0069, LATIN SMALL LETTER I */
  X_______,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_006A[ 10] = { /* code 006A, LATIN SMALL LETTER J */
  __X_____,
  ________,
  ________,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_006B[  8] = { /* code 006B, LATIN SMALL LETTER K */
  X_______,
  X_______,
  X_______,
  X__X____,
  X_X_____,
  XX______,
  X_X_____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_006C[  8] = { /* code 006C, LATIN SMALL LETTER L */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_006D[  5] = { /* code 006D, LATIN SMALL LETTER M */
  XXX_XXX_,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  X__X__X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_006E[  5] = { /* code 006E, LATIN SMALL LETTER N */
  XXXX____,
  X__X____,
  X__X____,
  X__X____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_006F[  5] = { /* code 006F, LATIN SMALL LETTER O */
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0070[  7] = { /* code 0070, LATIN SMALL LETTER P */
  X_XX____,
  XX__X___,
  X___X___,
  X___X___,
  XXXX____,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0071[  7] = { /* code 0071, LATIN SMALL LETTER Q */
  _XXX____,
  X__X____,
  X__X____,
  X__X____,
  _XXX____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0072[  5] = { /* code 0072, LATIN SMALL LETTER R */
  XXX_____,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0073[  5] = { /* code 0073, LATIN SMALL LETTER S */
  XXXX____,
  X_______,
  _XX_____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0074[  7] = { /* code 0074, LATIN SMALL LETTER T */
  _X______,
  _X______,
  XXXX____,
  _X______,
  _X______,
  _X______,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0075[  5] = { /* code 0075, LATIN SMALL LETTER U */
  X__X____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0076[  5] = { /* code 0076, LATIN SMALL LETTER V */
  X___X___,
  _X_X____,
  _X_X____,
  _X_X____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0077[  5] = { /* code 0077, LATIN SMALL LETTER W */
  X___X__X,
  _X__X_X_,
  _X_XX_X_,
  _XX_X_X_,
  __X__X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0078[  5] = { /* code 0078, LATIN SMALL LETTER X */
  X___X___,
  _X_X____,
  __X_____,
  _X_X____,
  X___X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_0079[  7] = { /* code 0079, LATIN SMALL LETTER Y */
  X___X___,
  _X_X____,
  _X_X____,
  _X_X____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_007A[  5] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXX___,
  ___X____,
  __X_____,
  _X______,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_007B[ 10] = { /* code 007B, LEFT CURLY BRACKET */
  _XX_____,
  _X______,
  _X______,
  _X______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_007C[ 10] = { /* code 007C, VERTICAL LINE */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_007D[ 10] = { /* code 007D, RIGHT CURLY BRACKET */
  XX______,
  _X______,
  _X______,
  _X______,
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_007E[  2] = { /* code 007E, TILDE */
  XX__X___,
  X_XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruan16_007F[  1] = { /* code 007F, <control> */
  ________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fontweiruan16_CharInfo[79] = {
   {   5,   8,   0,   4,   6, acGUI_Fontweiruan16_0030 } /* code 0030, DIGIT ZERO */
  ,{   3,   8,   1,   4,   6, acGUI_Fontweiruan16_0031 } /* code 0031, DIGIT ONE */
  ,{   4,   8,   1,   4,   6, acGUI_Fontweiruan16_0032 } /* code 0032, DIGIT TWO */
  ,{   4,   8,   1,   4,   6, acGUI_Fontweiruan16_0033 } /* code 0033, DIGIT THREE */
  ,{   6,   8,   0,   4,   6, acGUI_Fontweiruan16_0034 } /* code 0034, DIGIT FOUR */
  ,{   4,   8,   1,   4,   6, acGUI_Fontweiruan16_0035 } /* code 0035, DIGIT FIVE */
  ,{   5,   8,   1,   4,   6, acGUI_Fontweiruan16_0036 } /* code 0036, DIGIT SIX */
  ,{   4,   8,   1,   4,   6, acGUI_Fontweiruan16_0037 } /* code 0037, DIGIT SEVEN */
  ,{   5,   8,   0,   4,   6, acGUI_Fontweiruan16_0038 } /* code 0038, DIGIT EIGHT */
  ,{   5,   8,   0,   4,   6, acGUI_Fontweiruan16_0039 } /* code 0039, DIGIT NINE */
  ,{   1,   5,   1,   7,   2, acGUI_Fontweiruan16_003A } /* code 003A, COLON */
  ,{   2,   6,   0,   7,   2, acGUI_Fontweiruan16_003B } /* code 003B, SEMICOLON */
  ,{   5,   5,   1,   6,   7, acGUI_Fontweiruan16_003C } /* code 003C, LESS-THAN SIGN */
  ,{   5,   3,   1,   7,   7, acGUI_Fontweiruan16_003D } /* code 003D, EQUALS SIGN */
  ,{   5,   5,   1,   6,   7, acGUI_Fontweiruan16_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   4,   8,   1,   4,   5, acGUI_Fontweiruan16_003F } /* code 003F, QUESTION MARK */
  ,{   7,   8,   0,   4,   7, acGUI_Fontweiruan16_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   4,   8,   1,   4,   6, acGUI_Fontweiruan16_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   6,   8,   0,   4,   7, acGUI_Fontweiruan16_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   6,   8,   1,   4,   8, acGUI_Fontweiruan16_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   4,   8,   1,   4,   6, acGUI_Fontweiruan16_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   4,   8,   1,   4,   5, acGUI_Fontweiruan16_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   6,   8,   0,   4,   7, acGUI_Fontweiruan16_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   6,   8,   1,   4,   8, acGUI_Fontweiruan16_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   1,   8,   1,   4,   3, acGUI_Fontweiruan16_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   3,   8,   0,   4,   4, acGUI_Fontweiruan16_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   5,   8,   1,   4,   6, acGUI_Fontweiruan16_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   4,   8,   1,   4,   5, acGUI_Fontweiruan16_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{   8,   8,   1,   4,  10, acGUI_Fontweiruan16_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   6,   8,   1,   4,   8, acGUI_Fontweiruan16_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   7,   8,   0,   4,   8, acGUI_Fontweiruan16_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   5,   8,   1,   4,   6, acGUI_Fontweiruan16_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   8,   9,   0,   4,   8, acGUI_Fontweiruan16_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   6,   8,   1,   4,   7, acGUI_Fontweiruan16_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   5,   8,   1,   4,   6, acGUI_Fontweiruan16_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   5,   8,   1,   4,   6, acGUI_Fontweiruan16_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   5,   8,   1,   4,   7, acGUI_Fontweiruan16_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   7,   8,   0,   4,   7, acGUI_Fontweiruan16_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  10,   8,   0,   4,  10, acGUI_Fontweiruan16_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   6,   8,   0,   4,   6, acGUI_Fontweiruan16_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   6,   8,   0,   4,   6, acGUI_Fontweiruan16_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   6,   8,   0,   4,   6, acGUI_Fontweiruan16_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   2,  10,   1,   4,   3, acGUI_Fontweiruan16_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   4,   9,   0,   4,   4, acGUI_Fontweiruan16_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   2,  10,   0,   4,   3, acGUI_Fontweiruan16_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   5,   4,   1,   4,   7, acGUI_Fontweiruan16_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   4,   1,   0,  14,   4, acGUI_Fontweiruan16_005F } /* code 005F, LOW LINE */
  ,{   3,   2,   0,   4,   3, acGUI_Fontweiruan16_0060 } /* code 0060, GRAVE ACCENT */
  ,{   5,   5,   0,   7,   6, acGUI_Fontweiruan16_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   5,   8,   1,   4,   6, acGUI_Fontweiruan16_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   4,   5,   1,   7,   5, acGUI_Fontweiruan16_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   4,   8,   1,   4,   6, acGUI_Fontweiruan16_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   5,   5,   1,   7,   6, acGUI_Fontweiruan16_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   3,   8,   0,   4,   3, acGUI_Fontweiruan16_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   4,   7,   1,   7,   6, acGUI_Fontweiruan16_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   4,   8,   1,   4,   6, acGUI_Fontweiruan16_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   1,   8,   1,   4,   3, acGUI_Fontweiruan16_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   3,  10,  -1,   4,   3, acGUI_Fontweiruan16_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   4,   8,   1,   4,   5, acGUI_Fontweiruan16_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   1,   8,   1,   4,   3, acGUI_Fontweiruan16_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{   7,   5,   1,   7,   9, acGUI_Fontweiruan16_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   4,   5,   1,   7,   6, acGUI_Fontweiruan16_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   5,   5,   1,   7,   6, acGUI_Fontweiruan16_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   5,   7,   1,   7,   6, acGUI_Fontweiruan16_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   4,   7,   1,   7,   6, acGUI_Fontweiruan16_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   3,   5,   1,   7,   4, acGUI_Fontweiruan16_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   4,   5,   1,   7,   5, acGUI_Fontweiruan16_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   4,   7,   0,   5,   4, acGUI_Fontweiruan16_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   4,   5,   1,   7,   6, acGUI_Fontweiruan16_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   5,   5,   0,   7,   5, acGUI_Fontweiruan16_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{   8,   5,   0,   7,   8, acGUI_Fontweiruan16_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   5,   5,   0,   7,   5, acGUI_Fontweiruan16_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   5,   7,   0,   7,   5, acGUI_Fontweiruan16_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   5,   5,   0,   7,   5, acGUI_Fontweiruan16_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   3,  10,   0,   4,   3, acGUI_Fontweiruan16_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   1,  10,   1,   4,   3, acGUI_Fontweiruan16_007C } /* code 007C, VERTICAL LINE */
  ,{   3,  10,   0,   4,   3, acGUI_Fontweiruan16_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   5,   2,   1,   8,   7, acGUI_Fontweiruan16_007E } /* code 007E, TILDE */
  ,{   1,   1,   0,  12,   3, acGUI_Fontweiruan16_007F } /* code 007F, <control> */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontweiruan16_Prop2 = {
   0x0041 /* first character */
  ,0x007F /* last character  */
  ,&GUI_Fontweiruan16_CharInfo[ 16] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontweiruan16_Prop1 = {
   0x0030 /* first character */
  ,0x003F /* last character  */
  ,&GUI_Fontweiruan16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontweiruan16_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontweiruan16 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontweiruan16_Prop1}
  ,12 /* Baseline */
  ,5 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

